-- List of most important countries in the database.
INSERT INTO `countries` (`id`, `name`) VALUES 
('NL', 'Netherlands'),
('AT', 'Austria'),
('FR', 'France'),
('GB', 'United Kingdom'),
('FI', 'Finland'),
('DK', 'Denmark'),
('IE', 'Ireland'),
('IS', 'Iceland'),
('SE', 'Sweden'),
('IT', 'Italy'),
('ES', 'Spain'),
('PL', 'Poland'),
('BE', 'Belgium'),
('PT', 'Portugal'),
('NO', 'Norway'),
('CH', 'Switzerland'),
('MA', 'Morocco'),
('TR', 'Turkey'),
('BG', 'Bulgaria'),
('SN', 'Senegal'),
('GR', 'Greece'),
('HU', 'Hungary'),
('DZ', 'Algeria'),
('RU', 'Russian Federation'),
('RO', 'Romania'),
('DE', 'Germany'),
('TN', 'Tunesia'),
('AU', 'Australia'),
('ML', 'Mali'),
('VA', 'Holy See'),
('CZ', 'Czech Republic'),
('SK', 'Slovak Republic'),
('EG', 'Egypt'),
('EE', 'Estonia'),
('US', 'United States'),
('LV', 'Latvia'),
('UA', 'Ukraine'),
('KZ', 'Kazakhstan'),
('PK', 'Pakistan'),
('AF', 'Afghanistan'),
('LT', 'Lithuania'),
('KG', 'Kyrgyzstan'),
('SI', 'Slovenia'),
('BY', 'Belarus'),
('MD', 'Republic of Moldova'),
('JE', 'Jersey'),
('BA', 'Bosnia and Herzegovina'),
('HR', 'Croatia'),
('GE', 'Georgia'),
('AM', 'Armenia'),
('AZ', 'Azerbaijan'),
('BF', 'Burkina Faso'),
('MK', 'Macedonia'),
('AL', 'Albania'),
('LU', 'Luxembourg'),
('TM', 'Turkmenistan'),
('ME', 'Montenegro'),
('GG', 'Guernsey'),
('RS', 'Serbia');

INSERT INTO `former_countries` (`id`, `name`) VALUES 
('DDDE', 'DDR: German Dem. Rep.'),
('SUH', 'USSR'),
('YUCS', 'Yugoslavia'),
('CSHH', 'CSSR Czechoslovakia');
