START TRANSACTION;
INSERT INTO `species` (`euring_id`, `id`, `picture_url`, `info_url`, `name_nl`, `name_en`) VALUES 
(1860, 'Anas platyrhynchos', 'http://library.thinkquest.org/TQ0310822/images/mallard_male.jpg', 'http://animaldiversity.ummz.umich.edu/site/accounts/information/Anas_platyrhynchos.html', 'Wilde eend', 'Mallard'),
(1840, 'Anas crecca', 'http://www.abo.fi/~jlinden/japan/anacre2711.jpg', 'http://www.ivnvechtplassen.org/ivn_vogels_veen_weide/Wintertaling_Anas-crecca.html', 'Wintertaling', 'Teal'),
(1940, 'Anas clypeata', 'http://natuurbeleving.scene24.net/pictures/Slobeend_Anas-clypeata.jpg', 'http://animaldiversity.ummz.umich.edu/site/accounts/information/Anas_clypeata.html', 'Slobeend', 'Northern shovelers'),
(1790, 'Anas penelope', 'http://upload.wikimedia.org/wikipedia/commons/3/3f/Smient.jpg', 'http://nl.wikipedia.org/wiki/Smient', 'Smient', 'Wigeon'),
(1730, 'Tadorna tadorna', 'http://upload.wikimedia.org/wikipedia/commons/4/40/Tadorna_tadorna_%28aka%29.jpg', 'http://nl.wikipedia.org/wiki/Bergeend', 'Bergeend', 'Shelduck'),
(2130, 'Melanitta nigra', 'http://www.oiseaux.net/oiseaux/anseriformes/images/macreuse.noire.mila.2g.jpg', 'http://www.birdguides.com/html/vidlib/species/Melanitta_nigra.htm', 'Common Scoter', 'Zwarte Zee-eend'),
(1910, 'Anas querquedula', 'http://www.birdguides.com/html/vidlib/assetPictures/027098a001_j2.jpg', 'http://nl.wikipedia.org/wiki/Zomertaling', 'Zomertaling', 'Garganey'),
(1980, 'Aythya ferina', 'http://www.kolkatabirds.com/scommpochard.jpg', 'http://www.birdguides.com/html/vidlib/species/Aythya_ferina.htm', 'Tafeleend', 'Pochard'),
(2060, 'Somateria mollissima', 'http://www.vogeldagboek.nl/Afbeeldingen/Eider/Eider090606.jpg', 'http://www.ivnvechtplassen.org/ivn_vogels_niet_vechtstreek/Eidereend_Somateria-mollissima.html', 'Eidereend', 'Common Eider'),
(2030, 'Aythya fuligula', 'http://www.ivnvechtplassen.org/ivn_vogels_plas_moeras/Kuifeend_Aythya-fuligula.jpg', 'http://www.ivnvechtplassen.org/ivn_vogels_plas_moeras/Kuifeend_Aythya-fuligula.html', 'Kuifeend', 'Tufted Duck'),
(2180, 'Bucephala clangula', 'http://www.oiseaux.net/oiseaux/anseriformes/images/garrot.a.oeil.d.or.yvth.1g.jpg', 'http://www.vogelvisie.nl/soort/brilduiker.php', 'Brilduiker', 'Common Goldeneye'),
(1710, 'Tadorna ferrugnea', 'http://www.photodigiscoping.com/galeria/data/media/8/tarrocanelophd.jpg', 'http://www.birdguides.com/html/vidlib/species/Tadorna_ferruginea.htm', 'Casarca', 'Ruddy Shelduck'),
(1820, 'Anas strepera', 'http://www.haryana-online.com/images/Birds/FWS-Gadwall600.jpg', 'http://www.birdguides.com/html/vidlib/species/Anas_strepera.htm', 'Krakeend', 'Gadwall'),
(1890, 'Anas acuta', 'http://upload.wikimedia.org/wikipedia/commons/d/d7/Npintail09a.jpg', 'http://nl.wikipedia.org/wiki/Pijlstaart', 'Pijlstaart', 'Pintail'),
(2210, 'Mergus serrator', 'http://birdphotography.com/species/photos/rbme-4.jpg', 'http://www.birdguides.com/html/vidlib/species/Mergus_serrator.htm', 'Middelste Zaagbek', 'Red-breasted Merganser'),
(2040, 'Aythya marila', 'http://www.ivnvechtplassen.org/ivn_vogels_winter/Toppereend_Aythya-marila.jpg', 'http://www.ivnvechtplassen.org/ivn_vogels_winter/Toppereend_Aythya-marila.html', 'Toppereend', 'Scaup'),
(1960, 'Netta rufina', 'http://www.ittiofauna.org/provinciarezzo/caccia/tabelle_specie/anseriformi/fistione_turco/images/netta_rufina-400.jpg', 'http://www.birdguides.com/html/vidlib/species/Netta_rufina.htm', 'Krooneend', 'Red-crested Pochard'),
(1780, 'Aix galericulata', 'http://animaldiversity.ummz.umich.edu/site/resources/grzimek_birds/Anatidae/Aix_galericulata_male.jpg/medium.jpg', 'http://animaldiversity.ummz.umich.edu/site/accounts/information/Aix_galericulata.html', 'Mandarijneend', 'Manderin duck'),
(2190, 'Mergus cucullatus', 'http://www.hlasek.com/foto/mergus_cucullatus_32.jpg', 'http://www.audubon.org/bird/BoA/F40_G1c.html', 'Kuifzaagbek', 'The Hooded Merganser'),
(2230, 'Mergus merganser', 'http://www.ivnvechtplassen.org/ivn_vogels_winter/Grote_Zaagbek_Mergus-merganser.jpg', 'http://www.birdguides.com/html/vidlib/species/Mergus_merganser.htm', 'Grote Zaagbek', 'Red-breasted Merganser'),
(2020, 'Aythya nyroca', 'http://www.regione.emilia-romagna.it/laguna/repository_IMG/ADB002C3FF1367CC412567C5004878E7%23%23%23ATTD0SBI.jpg', 'http://www.birdguides.com/html/vidlib/species/Aythya_nyroca.htm', 'Witoogeend', 'Ferruginous Duck'),
(2200, 'Mergus albellus', 'http://www.hlasek.com/foto/mergus_albellus_ad9261.jpg', 'http://www.ivnvechtplassen.org/ivn_vogels_winter/Nonnetje_Mergus-albellus.html', 'Smew', 'Nonnetje'),
(2150, 'Melanitta fusca', 'http://klub.wz.cz/thnedy1.jpg', 'http://www.vogeldagboek.nl/Afbeeldingen2/Grote%20zee-eend/Grote%20zee-eend.html', 'Grote Zeeëend', 'Velvet Scoter  '),
(1800, 'Anas americana', 'http://www.hlasek.com/foto/anas_americana_10673.jpg', 'http://nl.wikipedia.org/wiki/Amerikaanse_smient', 'Amerikaanse Smient', 'American widgeon'),
(1770, 'Aix sponsa', 'http://static.flickr.com/54/133619638_9047e70739_b.jpg', 'http://nl.wikipedia.org/wiki/Carolina-eend', 'Carolina eend', 'North american wood duck'),
(1900, 'Anas bahamensis', 'http://www.hlasek.com/foto/anas_bahamensis_11221.jpg', 'http://nl.wikipedia.org/wiki/Bahamapijlstaart', 'Bahama pijlstaart', 'White-cheeked Pintail Bahama');
COMMIT;
